apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contract-first-camel-app-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: contract-first
spec:
  project: default
  source:
    repoURL: https://github.com/rrbanda/developer-charts
    targetRevision: HEAD
    path: quarkus-application
    helm:
      values: |
        system: contract-first
        component: camel-app
        environment: prod
        image:
          tag: latest
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: contract-first-prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m